### ISSUE TITLE
项目启动后提示./node_modules/_vue-i18n@9.2.2@vue-i18n/dist/vue-i18n.esm-bundler.js 2291:18-29 "export 'effectScope' was not found in 'vue'

### ISSUE THREAD

**Issue by zhenghj-zhj** [lss5270/vue-manage-system-plus#14]

**Comment by coffeeDanny** [comment]
跟您遇到了同样的问题，想请教下，您解决了吗？怎么解决的可以指导一下嘛？ 感谢感谢～～～

**Comment by coffeeDanny** [comment]
文件位置：src/plugins/element.js
修改内容：
 import { createI18n } from 'vue-i18n'  这一行
改为下面的
import { createI18n } from 'vue-i18n/index'

**Comment by Yutti7** [comment]
> 文件位置：src/plugins/element.js 修改内容： import { createI18n } from 'vue-i18n' 这一行 改为下面的 import { createI18n } from 'vue-i18n/index'

vue 改成 3.1.7就可以

**Comment by Aurora178** [comment]
> 

不行

**Comment by lss5270** [comment]
抱歉前阵子有点忙忘记看问题了，已经把vue版本升级到最新的3.2.41就能解决问题了~ 。或者更新完代码之后，重新执行一遍npm ci，再启动即可解决问题

**Comment by lss5270** [comment]
> > 
> 
> 不行

抱歉前阵子有点忙忘记看问题了，已经把vue版本升级到最新的3.2.41就能解决问题了~ 。或者更新完代码之后，重新执行一遍npm ci，再启动即可解决问题

**Comment by lss5270** [comment]
> _No description provided._

抱歉前阵子有点忙忘记看问题了，已经把vue版本升级到最新的3.2.41就能解决问题了~ 。或者更新完代码之后，重新执行一遍npm ci，再启动即可解决问题

**Comment by Aurora178** [comment]
> > > 
> > 
> > 
> > 不行
> 
> 抱歉前阵子有点忙忘记看问题了，已经把vue版本升级到最新的3.2.41就能解决问题了~ 。 或者更新完代码之后，重新执行一遍npm ci，再启动即可解决问题

好的，谢谢，   我稍后试一下
