### ISSUE TITLE
登录后，右侧的退出登录点击没反应。 

### ISSUE THREAD

**Issue by jack1ripper** [lss5270/vue-manage-system-plus#15]

**Comment by lss5270** [comment]
线上的测试地址（https://lss5270.github.io/vue-manage-system-plus-demo/#/login）亲测没问题，或者你可以打个断点看下自己本地的代码，看下是不是改动了哪里

> _No description provided._

**Comment by lss5270** [comment]
升级UI库之后就解决了。官方UI库的问题~。你重新拉一下配置文件，然后重新npm install就解决了
