### ISSUE TITLE
关于页面tab刷新和切换的问题

### ISSUE THREAD

**Issue by latelee** [lss5270/vue-manage-system-plus#2]
作者好！十分感谢有这个项目，之前没有接触过vue，属于新人，正在学习使用。现在有几个小问题请教一下。
1、点击左侧几个图标，可打开不同的页面，我在table页面输入一些数据时，切换到另外的页面，再切回来，我加的数据不见的，相当于table页面重新加载。如何实现可保留原页面已输入的数据呢？
2、当打开多个页面时，如果按F5刷新，会删除其它页面，只保留当前页面，这个是本身的特性，还是可以实现保留所有页面？

新手上路，可能有点冒昧。再次感谢！

**Comment by lss5270** [comment]
第一：要实现所提第一条，需要把数据缓存在本地，从其他页面切换过来时自动加载一遍数据就行了。切换页面时本来就是重新加载
第二：tabs标签页存储在vuex中，因为vuex本身属于js，所以全部变量都是存储在js内存中，F5刷新页面 会造成所有js变量都会清空释放。当然了也可以保留，就是要把tabs标签变量存储在本地，这样才能做到持久化存储。

**Comment by lss5270** [comment]
> 作者好！十分感谢有这个项目，之前没有接触过vue，属于新人，正在学习使用。现在有几个小问题请教一下。
> 1、点击左侧几个图标，可打开不同的页面，我在table页面输入一些数据时，切换到另外的页面，再切回来，我加的数据不见的，相当于table页面重新加载。如何实现可保留原页面已输入的数据呢？
> 2、当打开多个页面时，如果按F5刷新，会删除其它页面，只保留当前页面，这个是本身的特性，还是可以实现保留所有页面？
> 
> 新手上路，可能有点冒昧。再次感谢！

第一：要实现所提第一条，需要把数据缓存在本地，从其他页面切换过来时自动加载一遍数据就行了。切换页面时本来就是重新加载
第二：tabs标签页存储在vuex中，因为vuex本身属于js，所以全部变量都是存储在js内存中，F5刷新页面 会造成所有js变量都会清空释放。当然了也可以保留，就是要把tabs标签变量存储在本地，这样才能做到持久化存储。

**Comment by latelee** [comment]
感谢作者回复！我研究一下。

**Comment by lss5270** [comment]
> 感谢作者回复！我研究一下。

不客气，最近在处理小程序，所以工作有点忙 忘记及时回复了，过阵子不忙了，我再完善更新一下系统。可以先帮点个赞~

**Comment by latelee** [comment]
已start。
有网友fork并修改了代码 https://github.com/liyu022/vue-manage-system-plus。
因为我是初接触，发现2个仓库有些地方不同，各有我所需，但又不懂怎么整合。

**Comment by lss5270** [comment]
> 已start。
> 有网友fork并修改了代码 [https://github.com/liyu022/vue-manage-system-plus。](https://github.com/liyu022/vue-manage-system-plus%E3%80%82)
> 因为我是初接触，发现2个仓库有些地方不同，各有我所需，但又不懂怎么整合。

不要fork，他fork之后 提交推送的代码 我这边都能看得到的。他是把我那些参数变量什么的 改成自己公司的而已，并没有改动功能和底层

**Comment by lss5270** [comment]
> 已start。
> 有网友fork并修改了代码 [https://github.com/liyu022/vue-manage-system-plus。](https://github.com/liyu022/vue-manage-system-plus%E3%80%82)
> 因为我是初接触，发现2个仓库有些地方不同，各有我所需，但又不懂怎么整合。

不好意思哈，因为文件大小写改过，由于git自身大小写不敏感导致出现文件找不到的问题。已经重新提交了。你那边有报Home.vue找不到吗？
