### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by rongmome** [lss5270/vue-manage-system-plus#3]
This dependency was not found:

@/views/home.vue in ./src/router/index.js
...

**Comment by lss5270** [comment]
> This dependency was not found:
> 
> @/views/home.vue in ./src/router/index.js
> ...

源码没问题的，看下是不是自己删除了home.vue

**Comment by lss5270** [comment]
> This dependency was not found:
> 
> @/views/home.vue in ./src/router/index.js
> ...

不好意思哈，因为文件大小写改过，由于git自身大小写不敏感导致出的问题。已经重新提交了

**Comment by lss5270** [comment]
> This dependency was not found:
> 
> @/views/home.vue in ./src/router/index.js
> ...

Restoration has been completed.
