### ISSUE TITLE
vite

### ISSUE THREAD

**Issue by ylx252** [lss5270/vue-manage-system-plus#4]
希望
当前版本升级 到 vite2
例外一个ts版本

**Comment by lss5270** [comment]
> 希望
> 当前版本升级 到 vite2
> 例外一个ts版本

vue3是直接支持ts的

**Comment by ylx252** [comment]
hi 不好意思可能我没描述清楚还要求多，是 webpack 切换到 vite。在来个 ts 版。使用 vue-composition-api

**Comment by lss5270** [comment]
> position-api

你可以自己新起一个项目改版。我本人最近开发小程序有点忙噢

**Comment by lss5270** [comment]
> hi 不好意思可能我没描述清楚还要求多，是 webpack 切换到 vite。在来个 ts 版。使用 vue-composition-api

你可以自己新起一个项目改版。我本人最近开发小程序有点忙噢
