### ISSUE TITLE
You may need an additional loader to handle the result of these loaders

### ISSUE THREAD

**Issue by lixiangbiao** [lss5270/vue-manage-system-plus#7]
![image](https://user-images.githubusercontent.com/15979322/136329046-851448fc-1c70-4954-a648-ee8008b599dc.png)

**Comment by lss5270** [comment]
npm i or yarn

**Comment by lss5270** [comment]
代码多了一个ts，已提交。执行更新一下代码就行了，或者重新拉取代码
